export const palavras = [
    { termo: "Abraço", definicao: "Ato de envolver alguém com os braços, geralmente como demonstração de afeto.", endereco: 'abraco'},
    { termo: "Afeto", definicao: "Sentimento de carinho ou amor.", endereco: 'afeto'},
    { termo: "Amanhecer", definicao: "O nascer do sol; o início do dia.", endereco: 'amanhecer'},
    { termo: "Amizade", definicao: "Relação de carinho e afeto entre pessoas.", endereco: 'amanhecer'},
    { termo: "Aroma", definicao: "Odor agradável.", endereco: 'amora'},
    { termo: "Aurora", definicao: "Primeiro orvalho do dia; começo de algo.", endereco: 'aurora'},
    { termo: "Beleza", definicao: "Qualidade que agrada os sentidos ou a mente.", endereco: 'beleza'},
    { termo: "Bênção", definicao: "Ato de abençoar; graça divina.", endereco: 'bencao'},
    { termo: "Biblioteca", definicao: "Um conjunto de funções e recursos pré-escritos para uso em software.", endereco: 'biblioteca'},
    { termo: "Bolo", definicao: "Alimento doce, geralmente assado, feito com massa à base de farinha, ovos, açúcar e outros ingredientes, e frequentemente coberto com glacê ou recheio.", endereco: 'bolo'},
    { termo: "Borboleta", definicao: "Inseto com asas grandes e coloridas.", endereco: 'borboleta'},
    { termo: "Brisa", definicao: "Vento leve e suave.", endereco: 'brisa'},
    { termo: "Cachoeira", definicao: "Queda d'água natural.", endereco: 'cachoeira'},
    { termo: "Caminho", definicao: "Rota ou trilha a ser seguida.", endereco: 'caminho'},
    { termo: "Canto", definicao: "Ato de cantar; melodia.", endereco: 'canto'},
    { termo: "Céu", definicao: "Espaço acima da Terra, onde se veem as nuvens e as estrelas.", endereco: 'ceu'},
    { termo: "Chuva", definicao: "Precipitação de água em gotas da atmosfera.", endereco: 'chuva'},
    { termo: "Coragem", definicao: "Força moral para enfrentar o perigo ou o medo.", endereco: 'coragem'},
    { termo: "Dança", definicao: "Movimento rítmico do corpo.", endereco: 'danca'},
    { termo: "Deleite", definicao: "Grande prazer ou satisfação.", endereco: 'deleite'},
    { termo: "Doce", definicao: "Alimento com sabor açucarado.", endereco: 'doce'},
    { termo: "Doçura", definicao: "Qualidade de ser doce ou gentil.", endereco: 'docura'},
    { termo: "Elegância", definicao: "Qualidade de ser gracioso e estiloso.", endereco: 'elegante'},
    { termo: "Esperança", definicao: "Sentimento de expectativa e desejo de algo positivo.", endereco: 'esperanca'},
    { termo: "Espelho", definicao: "Superfície que reflete imagens.", endereco: 'espelho'},
    { termo: "Estrela", definicao: "Corpo celeste que brilha com luz própria.", endereco: 'estrela'},
    { termo: "Fantasia", definicao: "Imagem criada pela imaginação.", endereco: 'fantasia'},
    { termo: "Felicidade", definicao: "Estado de bem-estar e contentamento.", endereco: 'felicidade'},
    { termo: "Flor", definicao: "Parte reprodutiva de uma planta comumente colorida.", endereco: 'flor'},
    { termo: "Fruto", definicao: "Produto comestível de uma planta.", endereco: 'fruto'},
    { termo: "Gargalhada", definicao: "Risada alta e prolongada.", endereco: 'gargalhada'},
    { termo: "Gentileza", definicao: "Qualidade de ser gentil, amável.", endereco: 'gentileza'},
    { termo: "Gesto", definicao: "Movimento do corpo ou das mãos para expressar algo.", endereco: 'gesto'},
    { termo: "Gratidão", definicao: "Sentimento de agradecimento.", endereco: 'gratidao'},
    { termo: "Harmonia", definicao: "Combinação agradável de elementos.", endereco: 'harmonia'},
    { termo: "História", definicao: "Narrativa de eventos passados.", endereco: 'historia'},
    { termo: "Horizonte", definicao: "Linha onde o céu parece encontrar a terra ou o mar.", endereco: 'horizonte'},
    { termo: "Imaginação", definicao: "Capacidade de formar novas ideias e imagens na mente.", endereco: 'imaginacao'},
    { termo: "Inspiração", definicao: "Estímulo criativo.", endereco: 'inspiracao'},
    { termo: "Intuição", definicao: "Capacidade de compreender algo sem a necessidade de raciocínio.", endereco: 'intuicao'},
    { termo: "Inverno", definicao: "Estação do ano mais fria.", endereco: 'inverno'},
    { termo: "Janela", definicao: "Abertura em uma parede para permitir a entrada de luz e ar.", endereco: 'janela'},
    { termo: "Jardim", definicao: "Área cultivada com plantas e flores.", endereco: 'jardim'},
    { termo: "Jóia", definicao: "Objeto de valor usado como adorno.", endereco: 'joia'},
    { termo: "Lago", definicao: "Grande massa de água doce rodeada por terra.", endereco: 'lago'},
    { termo: "Leitura", definicao: "Ato de decifrar e compreender um texto.", endereco: 'leitura'},
    { termo: "Liberdade", definicao: "Estado de não estar preso ou restrito.", endereco: 'liberdade'},
    { termo: "Lua", definicao: "Satélite natural da Terra.", endereco: 'lua'},
    { termo: "Luz", definicao: "Energia eletromagnética que torna as coisas visíveis.", endereco: 'luz'},
    { termo: "Mar", definicao: "Grande extensão de água salgada.", endereco: 'mar'},
    { termo: "Melodia", definicao: "Sequência de notas musicais que formam um tema.", endereco: 'melodia'},
    { termo: "Memória", definicao: "Capacidade de reter e recordar informações.", endereco: 'memoria'},
    { termo: "Música", definicao: "Arte de combinar sons de forma agradável.", endereco: 'musica'},
    { termo: "Natureza", definicao: "O mundo físico e seus fenômenos.", endereco: 'natureza'},
    { termo: "Ninho", definicao: "Construção feita por aves para seus ovos.", endereco: 'ninho'},
    { termo: "Nostalgia", definicao: "Saudade de algo ou alguém do passado.", endereco: 'nostalgia'},
    { termo: "Nuvem", definicao: "Massa visível de gotículas de água suspensas na atmosfera.", endereco: 'nuvem'},
    { termo: "Oceano", definicao: "Grande massa de água salgada que cobre grande parte da Terra.", endereco: 'oceano'},
    { termo: "Ondas", definicao: "Movimento da água do mar.", endereco: 'ondas'},
    { termo: "Oração", definicao: "Pedido ou súplica a uma divindade.", endereco: 'oracao'},
    { termo: "Ouro", definicao: "Metal precioso, amarelo e brilhante.", endereco: 'ouro'},
    { termo: "Pão", definicao: "Alimento básico feito de farinha (geralmente de trigo), água e levedura, amassado e assado.", endereco: 'pao'},
    { termo: "Pássaro", definicao: "Animal vertebrado com penas e asas, capaz de voar.", endereco: 'passaro'},
    { termo: "Paz", definicao: "Estado de tranquilidade e ausência de conflitos.", endereco: 'paz'},
    { termo: "Pintura", definicao: "Obra de arte feita com tintas.", endereco: 'pintura'},
    { termo: "Poesia", definicao: "Arte de expressar ideias e emoções em versos.", endereco: 'poesia'},
    { termo: "Prédio", definicao: "Edificação de vários andares destinada a habitação, escritórios ou outros fins.", endereco: 'predio'},
    { termo: "Quadrinho", definicao: "Sequência de desenhos que contam uma história.", endereco: 'quadrinho'},
    { termo: "Quimera", definicao: "Criatura mitológica imaginária; ilusão.", endereco: 'quimera'},
    { termo: "Quietude", definicao: "Estado de calma e silêncio.", endereco: 'quietude'},
    { termo: "Refúgio", definicao: "Lugar que oferece proteção ou abrigo.", endereco: 'refugio'},
    { termo: "Rio", definicao: "Curso de água natural que flui para um oceano, lago ou outro rio.", endereco: 'rio'},
    { termo: "Risada", definicao: "Som de alegria e divertimento.", endereco: 'risada'},
    { termo: "Romance", definicao: "Gênero literário narrativo extenso.", endereco: 'romance'},
    { termo: "Sabedoria", definicao: "Conhecimento profundo e experiência.", endereco: 'sabedoria'},
    { termo: "Silêncio", definicao: "Ausência de som.", endereco: 'silencio'},
    { termo: "Sol", definicao: "Estrela central do nosso sistema planetário.", endereco: 'sol'},
    { termo: "Sonho", definicao: "Sucessão de imagens, ideias e emoções que ocorrem durante o sono.", endereco: 'sonho'},
    { termo: "Tempestade", definicao: "Fenômeno meteorológico caracterizado por ventos fortes e chuva intensa.", endereco: 'tempestade'},
    { termo: "Ternura", definicao: "Sentimento de carinho e afeto.", endereco: 'ternura'},
    { termo: "Terra", definicao: "Planeta em que vivemos.", endereco: 'terra'},
    { termo: "Tranquilidade", definicao: "Estado de calma e serenidade.", endereco: 'tranquilidade'},
    { termo: "União", definicao: "Ato de juntar ou combinar.", endereco: 'uniao'},
    { termo: "Universo", definicao: "A totalidade de toda a matéria, energia, planetas e estrelas.", endereco: 'universo'},
    { termo: "Utopia", definicao: "Lugar ou estado ideal, mas irrealizável.", endereco: 'utopia'},
    { termo: "Vagalume", definicao: "Inseto que emite luz.", endereco: 'vagalume'},
    { termo: "Vento", definicao: "Movimento do ar na atmosfera.", endereco: 'vento'},
    { termo: "Viagem", definicao: "Deslocamento de um lugar para outro.", endereco: 'viagem'},
    { termo: "Voz", definicao: "Som produzido pelas cordas vocais.", endereco: 'voz'},
    { termo: "Walkman", definicao: "Antigo aparelho portátil para ouvir música.", endereco: 'walkman'},
    { termo: "Whisky", definicao: "Bebida alcoólica destilada.", endereco: 'whisky'},
    { termo: "Xadrez", definicao: "Jogo de tabuleiro estratégico.", endereco: 'xadrez'},
    { termo: "Xerife", definicao: "Oficial de polícia em algumas regiões.", endereco: 'xerife'},
    { termo: "Xícara", definicao: "Pequeno recipiente com alça para beber líquidos.", endereco: 'xicara'},
    { termo: "Xilofone", definicao: "Instrumento musical de percussão.", endereco: 'xilofone'},
    { termo: "Yacht", definicao: "Barco de luxo para lazer.", endereco: 'yacht'},
    { termo: "Yoga", definicao: "Prática física, mental e espiritual.", endereco: 'yoga'},
    { termo: "Yogurte", definicao: "Alimento lácteo fermentado.", endereco: 'yorgute'},
    { termo: "Zelo", definicao: "Grande dedicação e cuidado.", endereco: 'zelo'},
    { termo: "Ziguezague", definicao: "Trajeto em forma de 'Z'.", endereco: 'ziguezague'},
    { termo: "Zumbido", definicao: "Som contínuo e monótono.", endereco: 'zumbido'},
  ];